sudo: required
services:
  - docker

before_install:
  - docker build -t eguerrero/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eguerrero/react-test npm test

after_success:
  - docker build -t eguerrero/multi-client ./client
  - docker build -t eguerrero/multi-nginx ./nginx
  - docker build -t eguerrero/multi-server ./server
  - docker build -t eguerrero/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eguerrero/multi-client
  - docker push eguerrero/multi-nginx
  - docker push eguerrero/multi-server
  - docker push eguerrero/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  app: multi-docker-2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-us-east-1-262731585638
  bucket_path: docker-multi
  on:
    branch: master